//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct("Cake.SqlServer")]
[assembly: AssemblyVersion("1.6.1.0")]
[assembly: AssemblyFileVersion("1.6.1.0")]
[assembly: AssemblyInformationalVersion("1.6.1-bugfix-warnings.1+5.Branch.bugfix/warnings.Sha.90c7ef53b11da28ccd518b9d96960c381fc36404")]
[assembly: AssemblyCopyright("Copyright (c) 2016 - 2016 AMV Software")]

[assembly: InternalsVisibleTo("Tests")]